<div id="divAddModifyNodegroupNodeOverride">
 <div class="hd"></div>
 <div class="bd">
<form name="formAddModifyNodegroupNodeOverride" method="POST" action="/api/w/v2/addmodify_nodegroup_node_override.php">
<input type="hidden" name="nodegroup">
<input type="hidden" name="service_id">
<table width="99%">
 <tr>
  <td><label for="node">Node</label></td>
  <td><input type="text" name="node" size="30"></td>
 </tr>
 <tr>
  <td><label for="enabled">Enabled:</label></td>
  <td>
<select name="enabled">
 <option value=""></option>
 <option value="0">0</option>
 <option value="1">1</option>
</select>
  </td>
 </tr>
 <tr>
  <td><label for="notifications">Notifications:</label></td>
  <td>
<select name="notifications">
 <option value=""></option>
 <option value="0">0</option>
 <option value="1">1</option>
</select>
  </td>
 </tr>
</table> 
</form>
 </div>
</div>
